export const FETCH_AUTHORS_BEGIN   = 'FETCH_AUTHORS_BEGIN';
export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_FAILURE = 'FETCH_AUTHORS_FAILURE';
export const LOGIN_STARTED  = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR= 'LOGIN_ERROR';
export const LOGGED_OUT= 'LOGGED_OUT';
export const UPDATE_REQUESTS= 'UPDATE_REQUESTS';
export const AUTHOR_SELECTED= 'AUTHOR_SELECTED';
export const REQUEST_SEND= 'REQUEST_SEND';
export const SAVE_MESSAGE= 'SAVE_MESSAGE';


